services:
  - type: web
    name: D-Treasures
    plan: free
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - .render.yaml
    envVars:
      - key: DB_URL
        value: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12788235
      - key: DB_USERNAME
        value: sql12788235
      - key: DB_PASSWORD
        value: 8IRtuLD4ny
    runtime: docker
